In [2]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
ad=pd.read_csv("C:/Users/Nikhil Sukthe/Downloads/iris.csv")

In [4]:
ad.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
ad.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [7]:
import category_encoders as ce

In [9]:
encoder=ce.OrdinalEncoder(cols=["Species"])

ad=encoder.fit_transform(ad)

In [10]:
ad.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int32
dtype: object

In [11]:
ad.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
ad_train,ad_test=train_test_split(ad,test_size=0.2,random_state=2)

In [14]:
ad_train.reset_index(drop=True,inplace=True)
ad_test.reset_index(drop=True,inplace=True)

In [16]:
x_train=ad_train.drop(["Species"],1)
x_test=ad_test.drop(["Species"],1)
y_train=ad_train["Species"]
y_test=ad_test["Species"]

In [19]:
from sklearn.ensemble import AdaBoostClassifier

In [21]:
model=AdaBoostClassifier(n_estimators=1,learning_rate=2,random_state=2)

In [22]:
model.fit(x_train,y_train)

AdaBoostClassifier(learning_rate=2, n_estimators=1, random_state=2)

In [23]:
y_pred=model.predict(x_test)

In [24]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [25]:
print("THE ACCURACY {0:0.04f}".format(accuracy_score(y_test,y_pred)*100))

THE ACCURACY 53.3333


In [27]:
cm=confusion_matrix(y_test,y_pred)
print("the confusion matrix:\n",cm)

the confusion matrix:
 [[ 0 14  0]
 [ 0  8  0]
 [ 0  0  8]]


In [30]:
print("correct prediction:",accuracy_score(y_test,y_pred))

correct prediction: 0.5333333333333333


In [31]:
print("correct prediction:",(1-accuracy_score(y_test,y_pred)))

correct prediction: 0.4666666666666667
