In [43]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [52]:
ca=pd.read_csv("C:/Users/Nikhil Sukthe/Downloads/car.csv")

In [53]:
ca.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [48]:
!pip install category_encoders

Defaulting to user installation because normal site-packages is not writeable


In [49]:
import category_encoders as ce 

In [57]:
encoder = ce.OrdinalEncoder(cols=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'])
ca= encoder.fit_transform(ca)

In [58]:
ca.dtypes

buying      int32
maint       int32
doors       int32
persons     int32
lug_boot    int32
safety      int32
class       int32
dtype: object

In [59]:
ca.head()

buying  maint  doors  persons  lug_boot  safety  class
0       1      1      1        1         1       1      1
1       1      1      1        1         1       2      1
2       1      1      1        1         1       3      1
3       1      1      1        1         2       1      1
4       1      1      1        1         2       2      1

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
ca_train,ca_test=train_test_split(ca,test_size=0.2,random_state=2)

In [63]:
ca_train.reset_index(drop=True,inplace=True)
ca_test.reset_index(drop=True,inplace=True)

In [67]:
x_train=ca_train.drop(['safety'],1)
x_test=ca_test.drop(['safety'],1)
y_train=ca_train['safety']
y_test=ca_test['safety']

In [69]:
from sklearn.tree import DecisionTreeClassifier

In [71]:
gn=DecisionTreeClassifier(criterion='gini',max_depth=3,random_state=0) 
gn.fit(x_train,y_train)


DecisionTreeClassifier(max_depth=3, random_state=0)

In [72]:
y_pred_gini =gn.predict(x_test)

In [74]:
from sklearn.metrics import accuracy_score

print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, y_pred_gini)))

Model accuracy score with criterion gini index: 0.4740


In [75]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_gini)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[77 38  0]
 [48 65 14]
 [30 52 22]]


In [76]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_gini))

              precision    recall  f1-score   support

           1       0.50      0.67      0.57       115
           2       0.42      0.51      0.46       127
           3       0.61      0.21      0.31       104

    accuracy                           0.47       346
   macro avg       0.51      0.46      0.45       346
weighted avg       0.50      0.47      0.45       346



In [77]:
submission=pd.DataFrame((list(y_pred_gini)),
                       columns=['safety'])

In [79]:
submission.to_csv(r'C:/Users/Nikhil Sukthe/Downloads/car.csv', index=False)