In [1]:
import pandas as pd 
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [2]:
hk=pd.read_csv("C:/Users/Nikhil Sukthe/Downloads/realest.csv")

In [3]:
hk.head()

Price  Bedroom   Space  Room   Lot     Tax  Bathroom  Garage  Condition
0   53.0      2.0   967.0   5.0  39.0   652.0       1.5     0.0        0.0
1   55.0      2.0   815.0   5.0  33.0  1000.0       1.0     2.0        1.0
2   56.0      3.0   900.0   5.0  35.0   897.0       1.5     1.0        0.0
3   58.0      3.0  1007.0   6.0  24.0   964.0       1.5     2.0        0.0
4   64.0      3.0  1100.0   7.0  50.0  1099.0       1.5     1.5        0.0

In [4]:
hk.dtypes

Price        float64
Bedroom      float64
Space        float64
Room         float64
Lot          float64
Tax          float64
Bathroom     float64
Garage       float64
Condition    float64
dtype: object

In [5]:
hk.isnull().sum()

Price         1
Bedroom       1
Space        11
Room          1
Lot          11
Tax          10
Bathroom      1
Garage        1
Condition     1
dtype: int64

In [6]:
hk.fillna(value=0,inplace=True)

In [7]:
hk.isnull().sum()

Price        0
Bedroom      0
Space        0
Room         0
Lot          0
Tax          0
Bathroom     0
Garage       0
Condition    0
dtype: int64

# HIERACHICAL ALGO

In [8]:
x=hk.drop(["Condition"],1)
y=hk["Condition"]

In [9]:
from sklearn.cluster import AgglomerativeClustering 

In [10]:
ac=AgglomerativeClustering(n_clusters=3,affinity='euclidean')

In [11]:
ac.fit(x)

AgglomerativeClustering(affinity='euclidean', n_clusters=3)

In [12]:
y_pred=ac.labels_
y_pred

array([0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [13]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [14]:

cm=confusion_matrix(y,y_pred)

In [15]:
print("THE CONFUSION MATRIX:\n",cm)

THE CONFUSION MATRIX:
 [[110   6   5]
 [ 30   6   0]
 [  0   0   0]]


In [16]:
print("ACCURACY SCORE:{0:0.04f}".format(accuracy_score(y,y_pred)*100))

ACCURACY SCORE:73.8854


In [17]:
from sklearn.cluster import KMeans

In [18]:

km=KMeans(n_clusters=2,init="k-means++",random_state=2)

In [19]:

km.fit(x)

KMeans(n_clusters=2, random_state=2)

In [20]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [21]:
print("the accuracy score:{0:0.04f}".format(accuracy_score(y,y_pred)*100))
cm=confusion_matrix(y,y_pred)
print("the confusion matrix:\n",cm)

the accuracy score:73.8854
the confusion matrix:
 [[110   6   5]
 [ 30   6   0]
 [  0   0   0]]
