In [ ]:
#### import pandas and numpy for data manipulation############

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
%cd C:\Users\Dell\Downloads

C:\Users\Dell\Downloads


In [ ]:
########## read data files########

In [3]:
ir1=pd.read_csv('Iris.csv')

In [4]:
ir1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
##### categorical data convert into numericals #############

In [5]:
import category_encoders as ce

In [6]:
encoder=ce.OrdinalEncoder(cols=['Species'])
ir1=encoder.fit_transform(ir1)

In [7]:
ir1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

In [ ]:
########## checking for Null values#######

In [8]:
ir1.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
###Spliting Train data into Train and Test data sets,
###train data is for model bulding,
###test data is for checking model performance.#############

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
ir1_train,ir1_test=train_test_split(ir1,test_size=0.2,random_state=2)

In [ ]:
####Rearranging index after random selection from train data set###

In [11]:
ir1_train.reset_index(drop=True,inplace=True)
ir1_test.reset_index(drop=True,inplace=True)

In [ ]:
###Splitting data to dependent variables data set and target variable data set####

In [12]:
x_train=ir1_train.drop(["Species"],1)
y_train=ir1_train["Species"]
x_test=ir1_test.drop(["Species"],1)
y_test=ir1_test["Species"]

In [ ]:
###### svm model buliding ######

In [13]:
    from sklearn.svm import SVC # "Support vector classifier"  
    classifier = SVC(kernel='linear', random_state=0)  
    classifier.fit(x_train, y_train)  

SVC(kernel='linear', random_state=0)

In [15]:
y_pred= classifier.predict(x_test)  

In [16]:
from sklearn.metrics import classification_report, confusion_matrix

In [17]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]


In [18]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8
           3       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [20]:
accuracy = accuracy_score(y_test, y_pred)*100
print('Accuracy of our model is' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is100.0 %.


In [ ]:
########### print both correct and wrong predictions ##########

In [21]:
print(" correct predicition",accuracy_score(y_test,y_pred))

print(" worng predicition",(1-accuracy_score(y_test,y_pred)))

 correct predicition 1.0
 worng predicition 0.0


In [ ]:
############### program ends ##########

In [22]:
submission=pd.DataFrame((list(y_pred)),
                       columns=['Species'])

In [23]:
submission.to_csv(r'C:\Users\Dell\Downloads\sample_iris2.csv', index=False)